'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FaCode, FaCopy, FaCheck, FaThumbsUp, FaThumbsDown, FaDownload, FaDatabase, FaUpload, FaEdit } from 'react-icons/fa';
import { SiPython, SiApachespark } from 'react-icons/si';

interface ETLCodeGeneratorProps {
  files: string[];
  assessmentData: any;
  businessRequirements?: string;
  onGenerated: (code: string) => void;
  onNext: () => void;
  onFeedback: (liked: boolean, comment?: string) => void;
}

export default function ETLCodeGenerator({ files, assessmentData, businessRequirements, onGenerated, onNext, onFeedback }: ETLCodeGeneratorProps) {
  const [generating, setGenerating] = useState(true);
  const [progress, setProgress] = useState(0);
  const [selectedLanguage, setSelectedLanguage] = useState<'python' | 'spark' | 'sql'>('python');
  const [generatedCode, setGeneratedCode] = useState('');
  const [copied, setCopied] = useState(false);
  const [showOptions, setShowOptions] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    generateCode();
  }, [selectedLanguage]);

  const generateCode = async () => {
    setGenerating(true);
    setProgress(0);

    for (let i = 0; i <= 100; i += 10) {
      await new Promise(resolve => setTimeout(resolve, 150));
      setProgress(i);
    }

    const code = getCodeTemplate(selectedLanguage);
    setGeneratedCode(code);
    setGenerating(false);
    onGenerated(code);
  };

  const getCodeTemplate = (language: string) => {
    const req = (businessRequirements ?? '').trim();
    const reqHeader = req
      ? `# Business requirements (user provided)\n# ${req.replace(/\n/g, '\n# ')}\n\n`
      : '';

    const pythonCode = `import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime

${reqHeader}# Generated by Agent DHARA

class DataETL:
    def __init__(self, connection_string):
        self.engine = create_engine(connection_string)
        self.data_frames = {}
        
    def extract_data(self):
        """Extract data from database"""
        print("Starting data extraction...")
        ${files.map(file => `
        # Extract ${file}
        self.data_frames['${file}'] = pd.read_sql_table('${file}', self.engine)
        print(f"Extracted {len(self.data_frames['${file}'])} rows from ${file}")
        `).join('\n        ')}
        
    def transform_data(self):
        """Transform and clean data"""
        print("Starting data transformation...")
        
        for table_name, df in self.data_frames.items():
            print(f"\\nTransforming {table_name}...")
            
            # Remove duplicates
            before_count = len(df)
            df = df.drop_duplicates()
            print(f"  - Removed {before_count - len(df)} duplicates")
            
            # Handle missing values
            for col in df.columns:
                null_count = df[col].isnull().sum()
                if null_count > 0:
                    if df[col].dtype in ['float64', 'int64']:
                        df[col].fillna(df[col].median(), inplace=True)
                    else:
                        df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 'Unknown', inplace=True)
                    print(f"  - Filled {null_count} missing values in {col}")
            
            # Data type conversions
            for col in df.columns:
                if 'date' in col.lower() or 'time' in col.lower():
                    try:
                        df[col] = pd.to_datetime(df[col])
                        print(f"  - Converted {col} to datetime")
                    except:
                        pass
            
            self.data_frames[table_name] = df
            
    def load_data(self, output_connection_string):
        """Load cleaned data to destination"""
        print("\\nLoading data to destination...")
        output_engine = create_engine(output_connection_string)
        
        for table_name, df in self.data_frames.items():
            df.to_sql(f'{table_name}_cleaned', output_engine, if_exists='replace', index=False)
            print(f"Loaded {len(df)} rows to {table_name}_cleaned")
            
    def generate_quality_report(self):
        """Generate data quality report"""
        report = {
            'timestamp': datetime.now().isoformat(),
            'tables': {}
        }
        
        for table_name, df in self.data_frames.items():
            report['tables'][table_name] = {
                'row_count': len(df),
                'column_count': len(df.columns),
                'missing_values': df.isnull().sum().sum(),
                'duplicate_rows': df.duplicated().sum(),
                'memory_usage': df.memory_usage(deep=True).sum() / 1024**2  # MB
            }
            
        return report

# Usage
if __name__ == "__main__":
    etl = DataETL('postgresql://user:password@localhost:5432/database')
    etl.extract_data()
    etl.transform_data()
    etl.load_data('postgresql://user:password@localhost:5432/cleaned_database')
    report = etl.generate_quality_report()
    print("\\nETL Process Complete!")
    print(report)
`;

    const sparkCode = `from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

class SparkETL:
    def __init__(self):
        self.spark = SparkSession.builder \\
            .appName("DataETL") \\
            .config("spark.sql.adaptive.enabled", "true") \\
            .getOrCreate()
        self.dataframes = {}
        
    def extract_data(self, jdbc_url, properties):
        """Extract data from database"""
        print("Starting data extraction...")
        ${files.map(file => `
        # Extract ${file}
        self.dataframes['${file}'] = self.spark.read.jdbc(
            url=jdbc_url,
            table='${file}',
            properties=properties
        )
        print(f"Extracted {self.dataframes['${file}'].count()} rows from ${file}")
        `).join('\n        ')}
        
    def transform_data(self):
        """Transform and clean data"""
        print("Starting data transformation...")
        
        for table_name, df in self.dataframes.items():
            print(f"\\nTransforming {table_name}...")
            
            # Remove duplicates
            df = df.dropDuplicates()
            
            # Handle missing values
            for col_name in df.columns:
                col_type = df.schema[col_name].dataType
                if isinstance(col_type, (IntegerType, DoubleType, FloatType)):
                    median_val = df.approxQuantile(col_name, [0.5], 0.01)[0]
                    df = df.fillna({col_name: median_val})
                else:
                    df = df.fillna({col_name: 'Unknown'})
            
            self.dataframes[table_name] = df
            
    def load_data(self, jdbc_url, properties):
        """Load cleaned data"""
        print("\\nLoading data to destination...")
        
        for table_name, df in self.dataframes.items():
            df.write.jdbc(
                url=jdbc_url,
                table=f'{table_name}_cleaned',
                mode='overwrite',
                properties=properties
            )
            print(f"Loaded {df.count()} rows to {table_name}_cleaned")

# Usage
if __name__ == "__main__":
    etl = SparkETL()
    jdbc_url = "jdbc:postgresql://localhost:5432/database"
    properties = {"user": "username", "password": "password", "driver": "org.postgresql.Driver"}
    
    etl.extract_data(jdbc_url, properties)
    etl.transform_data()
    etl.load_data(jdbc_url, properties)
    print("\\nETL Process Complete!")
`;

    const sqlCode = `-- ETL SQL Script
-- Extract, transform and load data using SQL

-- Step 1: Create staging/cleaned tables (remove duplicates, handle nulls)
${files.map(file => `
-- Process ${file}
CREATE TABLE ${file}_cleaned AS
SELECT DISTINCT *
FROM ${file};

-- Optional: Update nulls in ${file}_cleaned
-- UPDATE ${file}_cleaned SET column_name = COALESCE(column_name, default_value) WHERE column_name IS NULL;
`).join('\n')}

-- Step 2: Create summary view for reporting
CREATE OR REPLACE VIEW etl_summary AS
${files.map((file, i) => `SELECT '${file}' AS source_table, COUNT(*) AS row_count FROM ${file}_cleaned${i < files.length - 1 ? '\nUNION ALL' : ''}`).join('\n')};

-- Step 3: Load to destination (example: insert into target schema)
${files.map(file => `
-- INSERT INTO target_schema.${file} SELECT * FROM ${file}_cleaned;
`).join('')}

-- Execute in order: run each section against your database
`;

    return language === 'python' ? pythonCode : language === 'spark' ? sparkCode : sqlCode;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleUpload = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.py,.sql,.txt';
    input.onchange = (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = () => {
        const text = reader.result as string;
        setGeneratedCode(text);
        onGenerated(text);
      };
      reader.readAsText(file);
    };
    input.click();
  };

  const handleEditToggle = () => {
    setIsEditing(!isEditing);
    if (isEditing) onGenerated(generatedCode);
  };

  const handleDownload = () => {
    const extension = selectedLanguage === 'sql' ? 'sql' : selectedLanguage === 'spark' ? 'py' : 'py';
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `etl_code.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleLike = () => {
    onFeedback(true);
    setShowOptions(true);
  };

  const handleDislike = () => {
    const comment = prompt('What would you like us to improve in the ETL code?');
    onFeedback(false, comment || undefined);
    
    setTimeout(() => {
      alert('Thank you! Regenerating improved ETL code...');
      generateCode();
    }, 500);
  };

  if (generating) {
    return (
      <div className="space-y-6">
        <div className="text-center">
          <h2 className="text-3xl font-bold text-zinc-900 mb-2">Generating ETL Code</h2>
          <p className="text-black/60">Creating optimized data pipeline code</p>
        </div>

        <div className="space-y-4">
          <div className="relative h-4 bg-black/10 rounded-full overflow-hidden">
            <motion.div
              className="h-full bg-gradient-to-r from-[#0070AD] to-[#12ABDB]"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>
          <div className="text-center text-2xl font-bold text-[#0070AD]">{progress}%</div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-zinc-900 mb-2">ETL Code Generated</h2>
          <p className="text-black/60">Review and download your ETL pipeline code</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleLike}
            className="p-3 bg-[#0070AD]/10 text-[#0070AD] rounded-lg hover:bg-[#0070AD]/15 transition-colors"
          >
            <FaThumbsUp className="text-xl" />
          </button>
          <button
            onClick={handleDislike}
            className="p-3 bg-red-500/20 text-red-400 rounded-lg hover:bg-red-500/30 transition-colors"
          >
            <FaThumbsDown className="text-xl" />
          </button>
        </div>
      </div>

      {/* Language Selector */}
      <div className="flex flex-wrap gap-3">
        {[
          { id: 'python', label: 'Python/Pandas', icon: SiPython },
          { id: 'spark', label: 'PySpark', icon: SiApachespark },
          { id: 'sql', label: 'SQL', icon: FaDatabase },
        ].map(({ id, label, icon: Icon }) => (
          <button
            key={id}
            onClick={() => setSelectedLanguage(id as any)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all ${
              selectedLanguage === id
                ? 'bg-[#0070AD] text-white'
                : 'bg-white/90 text-black/70 hover:bg-white border border-black/10'
            }`}
          >
            <Icon />
            {label}
          </button>
        ))}
      </div>

      {/* Code actions: Download, Upload, Edit */}
      <div className="flex flex-wrap gap-3">
        <motion.button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-black/10 bg-white/90 text-zinc-900 font-medium hover:bg-white hover:border-[#0070AD]/30 transition-colors"
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          <FaDownload className="w-4 h-4" />
          Download
        </motion.button>
        <motion.button
          onClick={handleUpload}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-black/10 bg-white/90 text-zinc-900 font-medium hover:bg-white hover:border-[#0070AD]/30 transition-colors"
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          <FaUpload className="w-4 h-4" />
          Upload
        </motion.button>
        <motion.button
          onClick={handleEditToggle}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg border font-medium transition-colors ${
            isEditing
              ? 'border-[#0070AD]/60 bg-[#0070AD]/10 text-[#0070AD]'
              : 'border-black/10 bg-white/90 text-zinc-900 hover:bg-white hover:border-[#0070AD]/30'
          }`}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          <FaEdit className="w-4 h-4" />
          {isEditing ? 'Save & Done' : 'Edit'}
        </motion.button>
      </div>

      {/* Code Display */}
      <div className="relative">
        <div className="absolute top-4 right-4 flex gap-2 z-10">
          <button
            onClick={handleDownload}
            className="p-2 bg-black/50 text-white rounded-lg hover:bg-black/60 transition-colors"
            title="Download code"
          >
            <FaDownload />
          </button>
          <button
            onClick={handleCopy}
            className="p-2 bg-black/50 text-white rounded-lg hover:bg-black/60 transition-colors"
            title="Copy to clipboard"
          >
            {copied ? <FaCheck /> : <FaCopy />}
          </button>
        </div>
        {isEditing ? (
          <textarea
            value={generatedCode}
            onChange={(e) => setGeneratedCode(e.target.value)}
            className="w-full bg-black text-white/90 p-6 rounded-lg font-mono text-sm resize-y min-h-96 max-h-[32rem] border border-white/10 focus:border-[#0070AD]/40 focus:ring-1 focus:ring-[#0070AD]/20 outline-none"
            spellCheck={false}
          />
        ) : (
          <pre className="options-scroll bg-black text-white/90 p-6 rounded-lg overflow-x-auto max-h-96 overflow-y-auto">
            <code>{generatedCode}</code>
          </pre>
        )}
      </div>

      {/* Options */}
      {showOptions && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          <div className="p-6 bg-white/90 border border-black/10 rounded-lg">
            <h3 className="text-xl font-bold text-zinc-900 mb-4">Would you like to work on duplicate data?</h3>
            <p className="text-black/60 mb-4">
              We can help clean your data and remove duplicates before running the ETL process.
            </p>
            <div className="flex flex-wrap gap-4">
              <button
                onClick={onNext}
                className="px-6 py-3 bg-[#0070AD] text-white rounded-xl font-semibold hover:bg-[#12ABDB] transition-colors"
              >
                Yes, Clean My Data
              </button>
              <button
                onClick={() => alert('Code is ready to use! Download and run it in your environment.')}
                className="px-6 py-3 bg-white border border-black/10 text-zinc-900 rounded-xl font-semibold hover:border-[#0070AD]/30 transition-colors"
              >
                No, Code is Enough
              </button>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
